# Generated by Django 3.2.18 on 2024-01-02 15:04

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('server', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('email_iq', models.CharField(blank=True, max_length=255, null=True)),
                ('password_iq', models.CharField(blank=True, max_length=255, null=True)),
                ('iq_option_instance', models.TextField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.JSONField(blank=True, null=True)),
                ('mercado_otc', models.JSONField(blank=True, null=True)),
                ('fecha_y_hora', models.DateTimeField(blank=True, null=True)),
                ('pase', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.JSONField(blank=True, null=True)),
                ('mercado_otc', models.JSONField(blank=True, null=True)),
                ('fecha_y_hora', models.DateTimeField(blank=True, null=True)),
                ('pase', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.JSONField(blank=True, null=True)),
                ('mercado_otc', models.JSONField(blank=True, null=True)),
                ('fecha_y_hora', models.DateTimeField(blank=True, null=True)),
                ('pase', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.JSONField(blank=True, null=True)),
                ('mercado_otc', models.JSONField(blank=True, null=True)),
                ('fecha_y_hora', models.DateTimeField(blank=True, null=True)),
                ('pase', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.JSONField(blank=True, null=True)),
                ('mercado_otc', models.JSONField(blank=True, null=True)),
                ('fecha_y_hora', models.DateTimeField(blank=True, null=True)),
                ('pase', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.JSONField(blank=True, null=True)),
                ('mercado_otc', models.JSONField(blank=True, null=True)),
                ('fecha_y_hora', models.DateTimeField(blank=True, null=True)),
                ('pase', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.JSONField(blank=True, null=True)),
                ('mercado_otc', models.JSONField(blank=True, null=True)),
                ('fecha_y_hora', models.DateTimeField(blank=True, null=True)),
                ('pase', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.JSONField(blank=True, null=True)),
                ('mercado_otc', models.JSONField(blank=True, null=True)),
                ('fecha_y_hora', models.DateTimeField(blank=True, null=True)),
                ('pase', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.JSONField(blank=True, null=True)),
                ('mercado_otc', models.JSONField(blank=True, null=True)),
                ('fecha_y_hora', models.DateTimeField(blank=True, null=True)),
                ('pase', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=191)),
                ('email', models.EmailField(max_length=254)),
                ('postal_code', models.IntegerField()),
                ('address', models.CharField(max_length=191)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foro_id', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foro_id', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisa', models.CharField(blank=True, max_length=100, null=True)),
                ('ganancia', models.CharField(blank=True, max_length=100, null=True)),
                ('martingala', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('modo', models.CharField(blank=True, max_length=100, null=True)),
                ('estrategia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo', models.CharField(max_length=500, null=True)),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('estado', models.CharField(blank=True, max_length=40, null=True)),
                ('mensaje', models.TextField(null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('importe', models.CharField(blank=True, max_length=10, null=True)),
                ('martingala', models.CharField(blank=True, choices=[('0', '0 Mg'), ('1', '1 Mg'), ('2', '2 Mg'), ('3', '3 Mg'), ('4', '4 Mg'), ('5', '5 Mg')], max_length=10, null=True)),
                ('tipo_martingala', models.CharField(blank=True, choices=[('double', 'Double'), ('single', 'Single')], max_length=10, null=True)),
                ('num_operaciones', models.IntegerField(blank=True, null=True)),
                ('modo_entrada', models.CharField(blank=True, choices=[('vela2', 'Vela 2'), ('vela3', 'Vela 3'), ('vela4', 'Vela 4'), ('vela5', 'Vela 5')], max_length=10, null=True)),
                ('after_loss', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=10, null=True)),
                ('after_loss_num', models.IntegerField(blank=True, null=True)),
                ('after_loss_martingala', models.CharField(blank=True, choices=[('0', '0 Mg'), ('1', '1 Mg'), ('2', '2 Mg'), ('3', '3 Mg'), ('4', '4 Mg')], max_length=10, null=True)),
                ('stop_gain', models.IntegerField(blank=True, null=True)),
                ('stop_loss', models.IntegerField(blank=True, null=True)),
                ('voto', models.IntegerField(blank=True, null=True)),
                ('enlace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.foro')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(blank=True, null=True)),
                ('martingala', models.CharField(blank=True, max_length=100, null=True)),
                ('cuadrante', models.CharField(blank=True, max_length=100, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_mercado', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje', models.JSONField(blank=True, null=True)),
                ('lista', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
