# Generated by Django 3.2.18 on 2024-01-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20240102_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicadores', models.JSONField(blank=True, null=True)),
                ('fecha_y_hora', models.DateTimeField(blank=True, null=True)),
                ('pase', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Senal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senales', models.JSONField(blank=True, null=True)),
                ('fecha_y_hora', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
