# Generated by Django 4.1.3 on 2022-11-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dstecnologia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="calificacion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("grado", models.CharField(max_length=100)),
                ("semana", models.CharField(max_length=100)),
                ("mes", models.CharField(max_length=100)),
                ("nota", models.IntegerField()),
                ("extra_point", models.IntegerField()),
                ("comentario", models.CharField(max_length=100)),
            ],
        ),
    ]
