# Generated by Django 4.1.3 on 2022-11-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dstecnologia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calificacion",
            name="grado",
            field=models.CharField(
                choices=[
                    ("1th", "1th"),
                    ("2th", "2th"),
                    ("3th", "3th"),
                    ("4th", "4th"),
                    ("5th", "5th"),
                    ("6th", "6th"),
                ],
                default="4th",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="estudiantes",
            name="grado",
            field=models.CharField(
                choices=[
                    ("1th", "1th"),
                    ("2th", "2th"),
                    ("3th", "3th"),
                    ("4th", "4th"),
                    ("5th", "5th"),
                    ("6th", "6th"),
                ],
                default="4th",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="grado",
            name="nombre",
            field=models.CharField(
                choices=[
                    ("1th", "1th"),
                    ("2th", "2th"),
                    ("3th", "3th"),
                    ("4th", "4th"),
                    ("5th", "5th"),
                    ("6th", "6th"),
                ],
                default="4th",
                max_length=100,
            ),
        ),
    ]
