# Generated by Django 4.1.3 on 2022-11-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dstecnologia",
            "0002_alter_calificacion_grado_alter_estudiantes_grado_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calificacion",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("Inicial", "Inicial"),
                    ("Primaria", "Primaria"),
                    ("Secundaria", "Secundaria"),
                ],
                default="Basica",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="calificacion",
            name="seccion",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C")],
                default="A",
                max_length=100,
            ),
        ),
    ]
