# Generated by Django 4.1.3 on 2022-12-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dstecnologia", "0004_alter_calificacion_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calificacion",
            name="extra_point",
        ),
        migrations.AddField(
            model_name="calificacion",
            name="meta",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="calificacion",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("Inicial", "Inicial"),
                    ("Primaria", "Primaria"),
                    ("Secundaria", "Secundaria"),
                ],
                default="Primaria",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="calificacion",
            name="nota",
            field=models.CharField(
                choices=[
                    ("Logrado", "Logrado"),
                    ("En proceso", "En proceso"),
                    ("Iniciado", "Iniciado"),
                ],
                default="Iniciado",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="estudiantes",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("Inicial", "Inicial"),
                    ("Primaria", "Primaria"),
                    ("Secundaria", "Secundaria"),
                ],
                default="Primaria",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="grado",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("Inicial", "Inicial"),
                    ("Primaria", "Primaria"),
                    ("Secundaria", "Secundaria"),
                ],
                default="Primaria",
                max_length=100,
            ),
        ),
    ]
