# Generated by Django 4.1.5 on 2023-04-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dstecnologia", "0002_calificacion"),
        (
            "dstecnologia",
            "0005_remove_calificacion_extra_point_calificacion_meta_and_more",
        ),
    ]

    operations = []
